make clean:
	rm day9solution

run:
	g++ -O3 -std=c++17 day9.hpp day9.cpp Day9Aoc.cpp -o day9solution
	./day9solution input.txt 10

debug:
	g++ -O3 -std=c++17 day9.hpp day9.cpp Day9Aoc.cpp -o day9solution
	./day9solution input.txt

debug_V:
	g++ -O3 -std=c++17 day9.hpp day9.cpp Day9Aoc.cpp -o day9solution
	./day9solution input.txt

make:
	g++ -O3 -std=c++17 Day9Aoc.cpp -o day9solution

